version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: carumuch-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /Users/yeongmujo/Desktop/workSpace/rabbitmq-data:/var/lib/rabbitmq # TODO 현재 로컬에서 관리 중
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  ai-mock:
    image: fprh13/carumuch-mock-ai:0.0.1
    container_name: carumuch-ai-mock
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8081:8081"
